
Status: FAILED!
Reason: Unable to run encrypt.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 37, in <module>
    main()
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 28, in main
    distance = int(input("Enter the distance value (shift): "))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line

Timestamp: 2025-02-12 21:32:59.146919

Status: FAILED!
Reason: Unable to run encrypt.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 37, in <module>
    main()
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 28, in main
    distance = int(input("Enter the distance value (shift): "))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line

Timestamp: 2025-02-12 21:32:59.147095

Status: FAILED!
Reason: Unable to run encrypt.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 37, in <module>
    main()
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 28, in main
    distance = int(input("Enter the distance value (shift): "))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line

Timestamp: 2025-02-12 21:32:59.303502

Status: FAILED!
Reason: Unable to run encrypt.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 37, in <module>
    main()
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/9780357881019-fundamentals-of-python-3e-4428f93d-289b-423a-969b-da834b7c7c29/python/chapter4/ex01/encrypt.py", line 28, in main
    distance = int(input("Enter the distance value (shift): "))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line

Timestamp: 2025-02-12 21:32:59.303604
